### ISSUE TITLE
Support for using the same value multiple times

### ISSUE THREAD

**Issue by CasperWSchmidt** [OFark/InterpolatedStringFormatter#1]
Hi, 

I just stumbled upon this little gem and it's (almost) exactly what I need. However, I just found out that using the same variable multiple times requires adding it multiple times to the `Interpolate` method call.

Example:
```
var input = {monthAndYear:MMM}@{monthAndYear:yyyy};
var monthAndYear = new DateTime(2022, 10, 31);
var result = input.Interpolate(monthAndYear);
```
This results in an exception:
```
System.FormatException
Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at InterpolatedStringFormatter.InterpolatedStringFormatter.ToString()
```

But running this:
```
var input = {monthAndYear:MMM}@{monthAndYear:yyyy};
var monthAndYear = new DateTime(2022, 10, 31);
var result = input.Interpolate(monthAndYear, monthAndYear);
```
Works as expected.

Since I do not know the input in advance (which is the point of using this library in the first place) I don't know how many times `monthAndYear` needs to be added to the `Interpolate` method.

Instead it would be awesome to have support for re-using values.

I'm happy to make a PR (will do that in a minute)

**Comment by OFark** [comment]
Thanks for the PR, I'll have a look when I get a moment.

**Comment by OFark** [comment]
This has now been pushed to NuGet
